// Generates the README figures from measured data, in both themes from one
// source so light and dark cannot drift. Run: npm run build-figures
import { writeFileSync, mkdirSync } from 'node:fs';
import { measure } from './measure-accuracy.mjs';

const THEMES = {
  light: { ink: '#1a1211', mute: '#7a6a68', hair: '#ece4e2', tint: '#fdf3f2', card: '#FFFFFF', red: '#d92819', soft: '#f0a79f', grey: '#d8cfcd', face: '#FFFFFF' },
  dark:  { ink: '#f4efee', mute: '#9c8d8a', hair: '#332927', tint: '#241b1a', card: '#141010', red: '#ff4b3a', soft: '#8e3229', grey: '#4a3f3d', face: '#141010' },
};
const SANS = 'ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif';
const MONO = 'ui-monospace,SFMono-Regular,Menlo,monospace';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

mkdirSync(new URL('../assets/', import.meta.url), { recursive: true });
const write = (base, svgFor) => {
  for (const [theme, c] of Object.entries(THEMES)) {
    writeFileSync(new URL(`../assets/${base}-${theme}.svg`, import.meta.url), svgFor(c));
    console.log(`  assets/${base}-${theme}.svg`);
  }
};

const frame = (w, h, c, label, body) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="${esc(label)}">
  <rect width="${w}" height="${h}" rx="18" fill="${c.tint}"/>
  <rect x="0.5" y="0.5" width="${w - 1}" height="${h - 1}" rx="17.5" fill="none" stroke="${c.hair}"/>
${body}
</svg>`;
const kicker = (x, y, c, t) => `  <text x="${x}" y="${y}" font-family="${MONO}" font-size="15" fill="${c.mute}" letter-spacing="2.5">${t}</text>`;

// ---------- accuracy ----------
const acc = measure();
const meanB = Math.round(acc.reduce((s, r) => s + r.before, 0) / acc.length);
const meanA = Math.round(acc.reduce((s, r) => s + r.after, 0) / acc.length);
write('accuracy', (c) => {
  const X = 232, W = 720, ROW = 42, TOP = 108;
  const rows = acc.map((r, i) => {
    const y = TOP + i * ROW;
    return `  <text x="64" y="${y + 15}" font-family="${SANS}" font-size="17" fill="${c.ink}">${r.metro}</text>
  <rect x="${X}" y="${y}" width="${(W * r.before) / 100}" height="9" rx="4.5" fill="${c.grey}"/>
  <text x="${X + W + 16}" y="${y + 9}" font-family="${SANS}" font-size="13" fill="${c.mute}">${r.before}%</text>
  <rect x="${X}" y="${y + 14}" width="${(W * r.after) / 100}" height="9" rx="4.5" fill="${c.red}"/>
  <text x="${X + W + 16}" y="${y + 23}" font-family="${SANS}" font-size="13" font-weight="700" fill="${c.red}">${r.after}%</text>`;
  }).join('\n');
  const h = TOP + acc.length * ROW + 46;
  return frame(1200, h, c, `Share of points near each metro that resolve to it. Mean rises from ${meanB}% with the nearest-big-place heuristic to ${meanA}% with city clubbing. ` + acc.map((r) => `${r.metro} ${r.before} to ${r.after}`).join('; '),
`${kicker(64, 52, c, 'SHARE OF POINTS THAT RESOLVE TO THE RIGHT METRO')}
  <rect x="232" y="66" width="10" height="9" rx="4.5" fill="${c.grey}"/><text x="252" y="75" font-family="${SANS}" font-size="14" fill="${c.mute}">nearest big place — mean ${meanB}%</text>
  <rect x="560" y="66" width="10" height="9" rx="4.5" fill="${c.red}"/><text x="580" y="75" font-family="${SANS}" font-size="14" fill="${c.ink}">clubbed to a city — mean ${meanA}%</text>
${rows}
  <text x="64" y="${h - 18}" font-family="${SANS}" font-size="13" fill="${c.mute}">Same points, same data, both rules — 121 samples within ~10 km of each centre. Generated by scripts/measure-accuracy.mjs.</text>`);
});

// ---------- the four rules ----------
const RULES = [
  ['Never across a state line', 'Delhi outweighs Noida from 20 km. But Noida is in Uttar Pradesh and is its own city.'],
  ['Districts weigh, they don’t rule', 'Obey them and Salt Lake leaves Kolkata. Ignore them and Noida joins Delhi. As a 1.6× weight, both are right.'],
  ['Size alone can’t spot a suburb', 'Ambattur is 10.04× smaller than Chennai and is one of its zones. Kalyan is 10.05× smaller than Mumbai and is not.'],
  ['So distance decides it', 'Ambattur sits inside Chennai’s footprint, Kalyan well outside Mumbai’s. Absorption needs both.'],
];
write('rules', (c) => {
  const cells = RULES.map((r, i) => {
    const x = 64 + (i % 2) * 568, y = 104 + Math.floor(i / 2) * 152;
    const words = r[1].split(' '); const lines = []; let cur = '';
    for (const w of words) { if ((cur + ' ' + w).trim().length > 52) { lines.push(cur.trim()); cur = w; } else cur += ' ' + w; }
    lines.push(cur.trim());
    return `  <rect x="${x}" y="${y}" width="504" height="128" rx="12" fill="${c.card}" stroke="${c.hair}"/>
  <circle cx="${x + 30}" cy="${y + 32}" r="13" fill="${c.red}"/>
  <text x="${x + 30}" y="${y + 37}" text-anchor="middle" font-family="${SANS}" font-size="14" font-weight="700" fill="${c.face}">${i + 1}</text>
  <text x="${x + 56}" y="${y + 37}" font-family="${SANS}" font-size="18" font-weight="700" fill="${c.ink}">${esc(r[0])}</text>
${lines.map((l, j) => `  <text x="${x + 24}" y="${y + 70 + j * 21}" font-family="${SANS}" font-size="14.5" fill="${c.mute}">${esc(l)}</text>`).join('\n')}`;
  }).join('\n');
  return frame(1200, 420, c, 'The four rules that decide which city a place belongs to: never across a state line; districts weigh rather than rule; size alone cannot spot a suburb; distance against the parent city footprint decides it.',
`${kicker(64, 52, c, 'FOUR RULES DECIDE WHERE A PLACE BELONGS')}
${cells}`);
});

// ---------- animated hero ----------
// Three real lookups, cycling. SMIL rather than a GIF: a few KB instead of
// megabytes, crisp at any size, and it animates inside <img> on GitHub.
const FRAMES = [
  ['12.9352, 77.6245', 'Bengaluru', 'Koramangala', 'Bangalore Urban district · Karnataka'],
  ['22.5800, 88.4200', 'Kolkata', 'Salt Lake City', 'North 24 Parganas district · West Bengal'],
  ['19.0770, 72.9986', 'Navi Mumbai', 'Vashi', 'Thane district · Maharashtra'],
];
const DUR = 10.5;
write('hero-animated', (c) => {
  const n = FRAMES.length;
  const groups = FRAMES.map((f, i) => {
    const a = i / n, b = (i + 1) / n, fade = 0.02;
    const kt = [0, Math.max(0, a - fade), a + fade, Math.max(a + fade, b - fade), Math.min(1, b + fade), 1];
    const vals = i === 0 ? '1;1;1;1;0;0' : '0;0;1;1;0;0';
    const keyTimes = i === 0 ? `0;${(b - fade).toFixed(4)};${(b - fade).toFixed(4)};${(b - fade).toFixed(4)};${(b + fade).toFixed(4)};1`
                             : kt.map((v) => Math.min(1, Math.max(0, v)).toFixed(4)).join(';');
    return `  <g opacity="${i === 0 ? 1 : 0}">
    <animate attributeName="opacity" values="${vals}" keyTimes="${keyTimes}" dur="${DUR}s" repeatCount="indefinite"/>
    <text x="88" y="122" font-family="${MONO}" font-size="22" fill="${c.ink}">${esc(f[0])}</text>
    <text x="664" y="132" font-family="${SANS}" font-size="58" font-weight="700" fill="${c.red}" letter-spacing="-1.6">${esc(f[1])}</text>
    <text x="666" y="170" font-family="${SANS}" font-size="17" fill="${c.ink}">${esc(f[2])}<tspan fill="${c.mute}"> · ${esc(f[3])}</tspan></text>
  </g>`;
  }).join('\n');
  return frame(1200, 330, c, `A latitude and longitude go in and the city it belongs to comes out. Examples: ${FRAMES.map((f) => `${f[2]} resolves to ${f[1]}`).join('; ')}. 621,128 places, 0.7 ms per lookup, zero dependencies.`,
`${kicker(64, 62, c, 'INPUT')}
  <rect x="64" y="82" width="272" height="64" rx="12" fill="${c.card}" stroke="${c.hair}"/>
  <path d="M360 114h58" stroke="${c.mute}" stroke-width="2" stroke-linecap="round"/><path d="M410 106l10 8-10 8" stroke="${c.mute}" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
  <g transform="translate(446 66) scale(0.72)">
    <path fill="${c.red}" d="M60 10C40.65 10 25 25.65 25 45c0 26.25 35 65 35 65s35-38.75 35-65c0-19.35-15.65-35-35-35z"/>
    <circle cx="48" cy="40" r="6.5" fill="${c.face}"/><circle cx="72" cy="40" r="6.5" fill="${c.face}"/>
    <path d="M47 56q13 12 26 0" fill="none" stroke="${c.face}" stroke-width="5" stroke-linecap="round"/>
  </g>
  <path d="M566 114h58" stroke="${c.mute}" stroke-width="2" stroke-linecap="round"/><path d="M616 106l10 8-10 8" stroke="${c.mute}" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
${kicker(664, 62, c, 'YOU ARE IN')}
${groups}
  <line x1="64" y1="224" x2="1136" y2="224" stroke="${c.hair}"/>
  <g font-family="${SANS}" font-size="19">
    <text x="64" y="274" fill="${c.red}" font-weight="700">621,128</text><text x="64" y="300" fill="${c.mute}" font-size="15">places, offline</text>
    <text x="316" y="274" fill="${c.red}" font-weight="700">0.7 ms</text><text x="316" y="300" fill="${c.mute}" font-size="15">per lookup</text>
    <text x="568" y="274" fill="${c.red}" font-weight="700">0</text><text x="568" y="300" fill="${c.mute}" font-size="15">dependencies, 0 API keys</text>
    <text x="884" y="274" fill="${c.red}" font-weight="700">${meanA}%</text><text x="884" y="300" fill="${c.mute}" font-size="15">metro accuracy, up from ${meanB}%</text>
  </g>`);
});

// ---------- social card ----------
writeFileSync(new URL('../assets/social-preview.svg', import.meta.url), (() => {
  const c = THEMES.light;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 640" width="1280" height="640">
  <rect width="1280" height="640" fill="${c.card}"/>
  <rect x="0" y="0" width="1280" height="640" fill="${c.tint}"/>
  <rect x="0" y="0" width="1280" height="10" fill="${c.red}"/>
  <g transform="translate(96 116) scale(1.15)">
    <path fill="${c.red}" d="M60 10C40.65 10 25 25.65 25 45c0 26.25 35 65 35 65s35-38.75 35-65c0-19.35-15.65-35-35-35z"/>
    <circle cx="48" cy="40" r="6.5" fill="${c.face}"/><circle cx="72" cy="40" r="6.5" fill="${c.face}"/>
    <path d="M47 56q13 12 26 0" fill="none" stroke="${c.face}" stroke-width="5" stroke-linecap="round"/>
  </g>
  <text x="252" y="196" font-family="${SANS}" font-size="76" font-weight="700" fill="${c.ink}" letter-spacing="-2">Nishaan</text>
  <text x="96" y="308" font-family="${SANS}" font-size="34" fill="${c.ink}">Coordinates in, the city you actually</text>
  <text x="96" y="352" font-family="${SANS}" font-size="34" fill="${c.ink}">belong to out.</text>
  <text x="96" y="410" font-family="${SANS}" font-size="24" fill="${c.mute}">No Google, no API keys, no external calls, no dependencies.</text>
  <line x1="96" y1="462" x2="1184" y2="462" stroke="${c.hair}"/>
  <g font-family="${SANS}">
    <text x="96"  y="522" font-size="38" font-weight="700" fill="${c.red}">621,128</text><text x="96"  y="556" font-size="20" fill="${c.mute}">places, offline</text>
    <text x="450" y="522" font-size="38" font-weight="700" fill="${c.red}">0.7 ms</text><text x="450" y="556" font-size="20" fill="${c.mute}">per lookup</text>
    <text x="800" y="522" font-size="38" font-weight="700" fill="${c.red}">${meanA}%</text><text x="800" y="556" font-size="20" fill="${c.mute}">metro accuracy</text>
  </g>
</svg>`;
})());
console.log('  assets/social-preview.svg');
